changeLogFile: changelog/db.changelog-master.yaml
url: jdbc:postgres://postgres:5432/postgres
username: postgres
password: postgrespassword
driver: org.postgresql.Driver
classpath: /liquibase/changelog/postgresql-42.2.23.jar